/* Browser-local sign-in. This is not a server security boundary. */
const TMS_ACCOUNTS_KEY='tms-local-accounts-v1';
let tmsSession=null,tmsAccountError='';
function tmsAccounts(){try{const value=localStorage.getItem(TMS_ACCOUNTS_KEY);if(value===null)return [];const rows=JSON.parse(value);if(!Array.isArray(rows)||rows.some(a=>!a.id||!a.username||!a.hash||!a.salt||!['administrator','coordinator','teacher','mentor'].includes(a.role)))throw Error('Invalid account data');return rows;}catch(e){throw Error('Account storage is unavailable or damaged. Restore access to this browser storage; existing data has not been reset.');}}
function tmsWriteAccounts(rows){localStorage.setItem(TMS_ACCOUNTS_KEY,JSON.stringify(rows));}
function tmsHex(bytes){return Array.from(bytes,b=>b.toString(16).padStart(2,'0')).join('');}
async function tmsPasswordHash(password,salt){if(!globalThis.crypto?.subtle)throw Error('Password protection needs a browser with Web Crypto. Open this file in a current browser, or serve it on localhost / HTTPS.');const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(password),'PBKDF2',false,['deriveBits']);return tmsHex(new Uint8Array(await crypto.subtle.deriveBits({name:'PBKDF2',salt:new TextEncoder().encode(salt),iterations:210000,hash:'SHA-256'},key,256)));}
function tmsUserId(value){const id=String(value||'').trim().toLowerCase();if(!/^[a-z0-9][a-z0-9._-]{2,39}$/.test(id))throw Error('User ID must be 3–40 letters, numbers, dots, underscores or hyphens.');return id;}
function tmsPasswordValid(password){if(password.length<10||password.length>128)throw Error('Use a password between 10 and 128 characters.');}
async function tmsNewAccount({username,password,name,role,faculty}){username=tmsUserId(username);tmsPasswordValid(password);name=String(name||'').trim();if(!name||name.length>100)throw Error('Enter a display name (up to 100 characters).');const rows=tmsAccounts();if(rows.some(a=>a.username===username))throw Error('This User ID already exists.');if(rows.length&&!tmsIsAdmin())throw Error('Only the administrator can create accounts.');if(!rows.length)role='administrator';if(!['administrator','coordinator','teacher','mentor'].includes(role))throw Error('Choose an account role.');if(role==='teacher'&&!state.faculty.some(f=>f.id===faculty))throw Error('Choose an existing teacher from Admin setup.');const salt=tmsHex(crypto.getRandomValues(new Uint8Array(16))),hash=await tmsPasswordHash(password,salt);const a={id:uid(),username,name,role,faculty:role==='teacher'?faculty:'',salt,hash,disabled:false};rows.push(a);tmsWriteAccounts(rows);return a;}
function tmsIsAdmin(){return tmsSession?.role==='administrator';}
function tmsApplyAccount(){const a=tmsSession;currentUser.viewAs=a.role==='teacher'?'teacher':a.role==='mentor'?'mentor':'stakeholder';currentUser.name=a.role==='teacher'?a.faculty:'';currentUser.coordinator=a.role==='teacher'?'':a.name;currentUser.stakeholder=currentUser.coordinator;}
function tmsBeginSession(a){tmsSession={...a};tmsApplyAccount();currentUser.role=a.role==='teacher'?'teacher':a.role==='mentor'?'attendance':'dashboard';activeSubTab.teacher='today';window.__tdTeacher=null;window.__ovPanel=null;window.studentEdit=null;smsStudent='';smsTab='overview';expandedRequestForm=null;sidebarOpen=false;document.getElementById('app').innerHTML='';render();if(a.role==='teacher')startGeoWatch();}
function tmsLogout(){stopGeoWatch();tmsSession=null;currentUser={role:'dashboard',name:'',center:'',coordinator:'',viewAs:'teacher',stakeholder:''};document.getElementById('app').innerHTML='';render();}
function tmsLoginScreen(){if(document.getElementById('tms-login-form'))return;let setup=false,error='';try{setup=tmsAccounts().length===0;}catch(e){error=e.message;}
 document.getElementById('app').innerHTML=`<main class="tms-auth"><div class="card tms-auth-card"><div class="brand-mark">TMS</div><h1 style="margin:18px 0 6px">Teacher Management System</h1><h3>${setup?'Create your administrator account':'Sign in to your account'}</h3><p class="hint">${setup?'Choose your own User ID and password. There is no default password.':'Enter the account details created in this browser.'}</p><form id="tms-login-form">${setup?'<label for="login-name">Your name</label><input id="login-name" name="name" autocomplete="name" required maxlength="100">':''}<label for="login-user">User ID</label><input id="login-user" name="username" autocomplete="username" required minlength="3" maxlength="40" pattern="[A-Za-z0-9][A-Za-z0-9._-]{2,39}" autocapitalize="none" spellcheck="false"><label for="login-password">Password</label><input id="login-password" name="password" type="password" autocomplete="${setup?'new-password':'current-password'}" required ${setup?'minlength="10"':''} maxlength="128">${setup?'<label for="login-confirm">Confirm password</label><input id="login-confirm" name="confirm" type="password" autocomplete="new-password" required minlength="10" maxlength="128">':''}<button class="btn btn-teal" style="width:100%;justify-content:center;margin-top:20px" ${error?'disabled':''}>${setup?'Create administrator account':'Sign in'}</button><p id="login-error" role="alert" style="color:var(--red)">${esc(error)}</p></form><p class="hint">Local sign-in only. Accounts and records stay in this browser. This page does not protect data from someone with access to browser storage.</p>${!setup?'<details><summary>Forgot your password?</summary><p class="hint">Ask your TMS administrator to reset it under User accounts. Administrator passwords have no recovery service in this local edition.</p></details>':''}</div></main>`;
 document.getElementById('tms-login-form').onsubmit=async e=>{e.preventDefault();const form=e.target,b=form.querySelector('button'),err=document.getElementById('login-error');if(b.disabled)return;b.disabled=true;err.textContent='';try{const username=form.elements.username.value,password=form.elements.password.value;let a;if(setup){if(password!==form.elements.confirm.value)throw Error('The passwords do not match.');a=await tmsNewAccount({username,password,name:form.elements.name.value,role:'administrator'});}else{a=tmsAccounts().find(x=>x.username===username.trim().toLowerCase()&&!x.disabled);const hash=await tmsPasswordHash(password,a?.salt||'invalid-user-placeholder');if(!a||hash!==a.hash)throw Error('Incorrect User ID or password.');if(a.role==='teacher'&&!state.faculty.some(f=>f.id===a.faculty))throw Error('Your teacher mapping is unavailable. Contact your administrator.');}tmsBeginSession(a);}catch(ex){err.textContent=ex.message;b.disabled=false;}};
}
renderPersonaBox=function(){const a=tmsSession;return `<div class="persona"><label>Signed in</label><strong>${esc(a?.name||'')}</strong><div class="p-note">${esc(a?.username||'')} · ${esc(a?.role||'')}</div><select id="persona-select" hidden disabled aria-hidden="true"><option></option></select><div class="cc-actions"><button class="btn btn-outline btn-sm" id="tms-password-btn">Change password</button><button class="btn btn-outline btn-sm" id="tms-logout">Sign out</button></div>${tmsIsAdmin()?'<button class="btn btn-teal btn-sm" id="tms-accounts-btn">User accounts</button>':''}</div>`;};
function tmsAccountPanel(){if(!tmsIsAdmin())return '';return `<div class="card"><h3>Create staff account</h3><p class="hint">Passwords require at least 10 characters. Give each staff member a unique User ID. Accounts work only in this browser.</p><form id="tms-create-user"><div class="form-grid">${smsField('User ID','username','text','','required minlength="3" maxlength="40" autocomplete="off"')}${smsField('Display name','name','text','','required maxlength="100"')}${smsField('Initial password','password','password','','required minlength="10" maxlength="128" autocomplete="new-password"')}${smsSelect('Role','role','<option value="teacher">Teacher</option><option value="mentor">Mentor</option><option value="coordinator">Coordinator</option><option value="administrator">Administrator</option>')}${smsSelect('Teacher mapping (teacher role only)','faculty',state.faculty.length?state.faculty.map(f=>`<option value="${esc(f.id)}">${esc(facultyDisplay(f.id))}</option>`).join(''):'<option value="">Add teachers in Admin setup first</option>')}</div><div class="cc-actions"><button class="btn btn-teal">Create account</button></div><p id="tms-account-message" role="status"></p></form></div><div class="card"><h3>Staff accounts</h3>${smsTable(['User ID','Name','Role','Status','Actions'],tmsAccounts().map(a=>`<tr><td>${esc(a.username)}</td><td>${esc(a.name)}</td><td>${esc(a.role)}${a.faculty?' · '+esc(a.faculty):''}</td><td>${a.disabled?'Disabled':'Active'}</td><td>${a.id!==tmsSession.id?`<button class="btn btn-outline btn-sm" data-account-toggle="${a.id}">${a.disabled?'Enable':'Disable'}</button> <button class="btn btn-outline btn-sm" data-account-reset="${a.id}">Reset password</button>`:'Current account'}</td></tr>`))}</div>`;}
function tmsPasswordPanel(target){const a=tmsAccounts().find(a=>a.id===target);if(!a||(!tmsIsAdmin()&&target!==tmsSession.id))return '';return `<div class="card"><h3>${target===tmsSession.id?'Change your password':'Reset password: '+esc(a.username)}</h3><form id="tms-change-password" data-target="${a.id}"><div class="form-grid">${target===tmsSession.id?smsField('Current password','current','password','','required autocomplete="current-password"'):''}${smsField('New password','newPassword','password','','required minlength="10" maxlength="128" autocomplete="new-password"')}${smsField('Confirm new password','confirmPassword','password','','required minlength="10" maxlength="128" autocomplete="new-password"')}</div><div class="cc-actions"><button class="btn btn-teal">Save password</button></div><p id="tms-password-message" role="status"></p></form></div>`;}
let tmsPasswordTarget='';
const tmsLoginBodyBase=renderBody;renderBody=function(){if(currentUser.role==='accounts')return tmsAccountPanel();if(currentUser.role==='password')return tmsPasswordPanel(tmsPasswordTarget);return tmsLoginBodyBase();};
const tmsLoginRenderBase=render;
render=function(){if(!tmsSession){tmsLoginScreen();return;}try{const a=tmsAccounts().find(a=>a.id===tmsSession.id);if(!a||a.disabled||a.hash!==tmsSession.hash){tmsLogout();return;}tmsSession={...a};}catch(e){tmsSession=null;tmsLoginScreen();return;}tmsApplyAccount();tmsLoginRenderBase();
 const selector=document.getElementById('persona-select');if(selector){selector.onchange=null;selector.disabled=true;}
 document.getElementById('tms-logout').onclick=tmsLogout;
 document.getElementById('tms-password-btn').onclick=()=>{tmsPasswordTarget=tmsSession.id;currentUser.role='password';render();};
 const accounts=document.getElementById('tms-accounts-btn');if(accounts)accounts.onclick=()=>{currentUser.role='accounts';render();};
 const create=document.getElementById('tms-create-user');if(create){const mapping=create.elements.faculty;mapping.required=create.elements.role.value==='teacher';create.elements.role.onchange=()=>{mapping.required=create.elements.role.value==='teacher';mapping.disabled=!mapping.required;};create.onsubmit=async e=>{e.preventDefault();const b=create.querySelector('button');if(b.disabled)return;b.disabled=true;try{await tmsNewAccount(Object.fromEntries(new FormData(create).entries()));render();showToast('Account created. Share the initial password privately.',5000);}catch(ex){document.getElementById('tms-account-message').textContent=ex.message;b.disabled=false;}};}
 document.querySelectorAll('[data-account-toggle]').forEach(b=>b.onclick=()=>{try{if(!tmsIsAdmin())return;const rows=tmsAccounts(),a=rows.find(a=>a.id===b.dataset.accountToggle);if(!a||a.id===tmsSession.id)return;a.disabled=!a.disabled;tmsWriteAccounts(rows);render();}catch(ex){showToast(ex.message);}});
 document.querySelectorAll('[data-account-reset]').forEach(b=>b.onclick=()=>{if(!tmsIsAdmin())return;tmsPasswordTarget=b.dataset.accountReset;currentUser.role='password';render();});
 const change=document.getElementById('tms-change-password');if(change)change.onsubmit=async e=>{e.preventDefault();const b=change.querySelector('button');if(b.disabled)return;b.disabled=true;const msg=document.getElementById('tms-password-message');try{const rows=tmsAccounts(),a=rows.find(a=>a.id===change.dataset.target);if(!a||(!tmsIsAdmin()&&a.id!==tmsSession.id))throw Error('Account unavailable.');if(a.id===tmsSession.id&&await tmsPasswordHash(change.elements.current.value,a.salt)!==a.hash)throw Error('Current password is incorrect.');const password=change.elements.newPassword.value;tmsPasswordValid(password);if(password!==change.elements.confirmPassword.value)throw Error('The passwords do not match.');a.salt=tmsHex(crypto.getRandomValues(new Uint8Array(16)));a.hash=await tmsPasswordHash(password,a.salt);tmsWriteAccounts(rows);if(a.id===tmsSession.id)tmsSession={...a};change.reset();msg.textContent='Password updated.';}catch(ex){msg.textContent=ex.message;}finally{b.disabled=false;}};
};
window.addEventListener('storage',e=>{if(e.key===TMS_ACCOUNTS_KEY&&tmsSession)render();});
