import http from 'node:http';
import {readFileSync} from 'node:fs';
import {fileURLToPath} from 'node:url';
import {openStore,readState,writeState,hashPassword,checkPassword,publicUser,userId,roles,token,digest,log,fail} from './store.mjs';
import {visible,mergeState,management} from './policy.mjs';
export async function createApp({dir,origin='http://127.0.0.1:3000',production=false}={}){
 const url=new URL(origin);if(url.origin!==origin)throw Error('APP_ORIGIN must be an exact origin without a trailing slash.');if(production&&url.protocol!=='https:')throw Error('Production requires an HTTPS APP_ORIGIN.');
 const db=openStore(dir),secure=url.protocol==='https:',cookieName=secure?'__Host-tms_session':'tms_session',dummy=await hashPassword(token());let signingIn=0;
 const html=readFileSync(new URL('./public/index.html',import.meta.url),'utf8');
 function json(res,status,value){res.writeHead(status,{'Content-Type':'application/json; charset=utf-8'});res.end(JSON.stringify(value));}
 function cookie(res,value,age){res.setHeader('Set-Cookie',`${cookieName}=${value}; Path=/; HttpOnly; SameSite=Strict; Max-Age=${age}${secure?'; Secure':''}`);}
 function current(req){const value=(req.headers.cookie||'').split(';').map(x=>x.trim()).find(x=>x.startsWith(cookieName+'='))?.slice(cookieName.length+1);if(!value||!/^[a-f0-9]{64}$/.test(value))return null;return db.prepare('SELECT users.*,sessions.hash AS session_hash,sessions.csrf FROM sessions JOIN users ON users.id=sessions.user_id WHERE sessions.hash=? AND sessions.expires>? AND users.disabled=0').get(digest(value),Date.now());}
 function audit(u,action){log(db,u?.username||'anonymous',action);}
 function limit(key,max){const now=Date.now();db.prepare('DELETE FROM attempts WHERE until<?').run(now);const r=db.prepare('SELECT * FROM attempts WHERE key=?').get(key);if(r&&r.count>=max)fail('Too many sign-in attempts. Try again in 15 minutes.',429);db.prepare('INSERT INTO attempts(key,count,until) VALUES(?,1,?) ON CONFLICT(key) DO UPDATE SET count=count+1').run(key,now+15*60*1000);}
 async function body(req){if(!String(req.headers['content-type']||'').startsWith('application/json'))fail('JSON required.',415);const authenticated=current(req);let size=0,chunks=[];const max=req.url==='/api/state'?8*1024*1024:16384;for await(const chunk of req){size+=chunk.length;if(size>max)fail('Request too large.',413);chunks.push(chunk);}if(authenticated&&!current(req))fail('Session was revoked. Sign in again.',401);try{return JSON.parse(Buffer.concat(chunks).toString());}catch{fail('Invalid JSON.');}}
 function csrf(req,u){if(req.headers.origin!==origin)fail('Request origin rejected.',403);if(u&&req.headers['x-csrf-token']!==u.csrf)fail('Session verification failed. Reload and try again.',403);}
 function admin(u){if(u.role!=='administrator')fail('Administrator access required.',403);}
 function session(res,u){const raw=token(),csrf=token();db.prepare('DELETE FROM sessions WHERE expires<?').run(Date.now());db.prepare('INSERT INTO sessions VALUES(?,?,?,?)').run(digest(raw),u.id,csrf,Date.now()+8*60*60*1000);cookie(res,raw,8*60*60);return {user:publicUser(u),csrf};}
 const server=http.createServer(async(req,res)=>{
  res.setHeader('Cache-Control','no-store');res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('Referrer-Policy','same-origin');res.setHeader('X-Frame-Options','DENY');res.setHeader('Permissions-Policy','camera=(), microphone=(), geolocation=(self)');if(secure)res.setHeader('Strict-Transport-Security','max-age=31536000');
  try{
   const path=new URL(req.url,origin).pathname,method=req.method;
   if(path==='/health'&&method==='GET')return json(res,200,{ok:true});
   if((path==='/'||path==='/index.html')&&method==='GET'){const nonce=token();res.setHeader('Content-Security-Policy',`default-src 'none'; script-src 'nonce-${nonce}'; style-src 'unsafe-inline' https://fonts.googleapis.com; font-src https://fonts.gstatic.com; img-src 'self' data:; connect-src 'self'; base-uri 'none'; frame-ancestors 'none'; form-action 'self'; object-src 'none'`);res.writeHead(200,{'Content-Type':'text/html; charset=utf-8'});return res.end(html.replaceAll('<script>',`<script nonce="${nonce}">`));}
   if(path==='/api/login'&&method==='POST'){
    csrf(req);limit('ip:'+digest(req.socket.remoteAddress||''),100);const b=await body(req);const username=typeof b.username==='string'?b.username.toLowerCase().trim():'';limit('user:'+digest(username),8);if(signingIn>=4)fail('Sign-in busy. Please try again shortly.',429);signingIn++;
    try{const u=db.prepare('SELECT * FROM users WHERE username=?').get(username);const ok=await checkPassword(b.password,u?.password||dummy);if(!u||u.disabled||!ok){audit(null,'Failed sign-in');fail('Incorrect User ID or password.',401);}db.prepare('DELETE FROM attempts WHERE key=?').run('user:'+digest(username));audit(u,'Signed in');return json(res,200,session(res,u));}finally{signingIn--;}
   }
   const u=current(req);if(!u)fail('Sign in to continue.',401);
   if(method!=='GET')csrf(req,u);
   if(path==='/api/me'&&method==='GET')return json(res,200,{user:publicUser(u),csrf:u.csrf});
   if(path==='/api/logout'&&method==='POST'){db.prepare('DELETE FROM sessions WHERE hash=?').run(u.session_hash);cookie(res,'',0);audit(u,'Signed out');return json(res,200,{ok:true});}
   if(path==='/api/password'&&method==='POST'){const b=await body(req);if(!await checkPassword(b.current,u.password))fail('Current password is incorrect.',400);const hashed=await hashPassword(b.password);db.prepare('UPDATE users SET password=?,must_change=0 WHERE id=?').run(hashed,u.id);db.prepare('DELETE FROM sessions WHERE user_id=?').run(u.id);audit(u,'Changed own password; sessions revoked');return json(res,200,session(res,{...u,password:hashed,must_change:0}));}
   if(u.must_change)fail('Change your initial password before opening records.',403);
   if(path==='/api/users'&&method==='GET'){admin(u);return json(res,200,{users:db.prepare('SELECT * FROM users ORDER BY username').all().map(publicUser)});}
   if(path==='/api/users'&&method==='POST'){admin(u);const b=await body(req),username=userId(b.username);if(typeof b.name!=='string'||!b.name.trim()||b.name.length>100||!roles.includes(b.role))fail('Enter a name and valid role.');if(b.role==='teacher'&&!readState(db).state.faculty.some(f=>f.id===b.faculty))fail('Choose a valid teacher mapping.');if(db.prepare('SELECT id FROM users WHERE username=?').get(username))fail('User ID already exists.',409);const hashed=await hashPassword(b.password);db.prepare('INSERT INTO users(id,username,name,role,faculty,password) VALUES(?,?,?,?,?,?)').run(token(),username,b.name.trim(),b.role,b.role==='teacher'?b.faculty:'',hashed);audit(u,'Created '+b.role+' account '+username);return json(res,201,{ok:true});}
   if(path.startsWith('/api/users/')&&method==='POST'){admin(u);const id=path.slice('/api/users/'.length),target=db.prepare('SELECT * FROM users WHERE id=?').get(id);if(!target)fail('Account not found.',404);if(target.id===u.id)fail('Use Change password for your own account.');const b=await body(req);if(b.action==='disable'||b.action==='enable')db.prepare('UPDATE users SET disabled=? WHERE id=?').run(b.action==='disable'?1:0,id);else if(b.action==='reset'){const hashed=await hashPassword(b.password);db.prepare('UPDATE users SET password=?,must_change=1 WHERE id=?').run(hashed,id);}else fail('Unknown account action.');db.prepare('DELETE FROM sessions WHERE user_id=?').run(id);audit(u,b.action+' account '+target.username);return json(res,200,{ok:true});}
   if(path==='/api/state'&&method==='GET'){const r=readState(db),view=visible(r.state,u);if(management(u)){const entries=db.prepare('SELECT * FROM audit ORDER BY id DESC LIMIT 300').all();view.smsAudit=entries.map(a=>({id:String(a.id),at:a.at,by:a.actor,action:a.action}));view.auditLog=entries.map(a=>({id:String(a.id),timestamp:a.at,actor:a.actor,action:a.action,details:''}));}return json(res,200,{revision:r.revision,state:view});}
   if(path==='/api/state'&&method==='PUT'){const b=await body(req),r=readState(db);if(b.revision!==r.revision)fail('Records changed in another session. Reload before saving.',409);const next=mergeState(r.state,b.state,u);writeState(db,next,r.revision);audit(u,'Saved '+u.role+' record changes');return json(res,200,{revision:r.revision+1,state:visible(next,u)});}
   if(path==='/api/teacher-attendance'&&method==='POST'){
    if(u.role!=='teacher')fail('Teacher access required.',403);const b=await body(req),r=readState(db),s=r.state.schedules.find(x=>x.id===b.id);if(!s||s.faculty!==u.faculty)fail('Session is not assigned to you.',403);
    const now=new Date(),date=now.toLocaleDateString('en-CA',{timeZone:'Asia/Kolkata'});if(s.date!==date)fail('Attendance is only available on the scheduled day.');
    if(s.mode!=='online'){const c=r.state.centers.find(c=>c.id===s.center);if(!c||!Number.isFinite(b.lat)||!Number.isFinite(b.lng)||Math.abs(b.lat)>90||Math.abs(b.lng)>180)fail('Location is required for this centre.');const rad=Math.PI/180,dl=(c.lat-b.lat)*rad,dg=(c.lng-b.lng)*rad,a=Math.sin(dl/2)**2+Math.cos(c.lat*rad)*Math.cos(b.lat*rad)*Math.sin(dg/2)**2;if(6371000*2*Math.atan2(Math.sqrt(a),Math.sqrt(1-a))>(c.radius||300))fail('You must be within the centre attendance radius.');}
    if(b.action==='entry'){if(s.status!=='scheduled'||r.state.schedules.some(x=>x.faculty===u.faculty&&x.status==='live')||r.state.requests.some(x=>x.scheduleId===s.id&&x.status==='pending'))fail('Session cannot be started now.');s.status='live';s.actualStart=now.toISOString();s.actualEnd=null;s.entryReview={status:'pending'};s.exitReview=null;}
    else if(b.action==='exit'){if(s.status!=='live')fail('Session is not live.');s.status='completed';s.actualEnd=now.toISOString();s.exitReview={status:'pending'};for(const key of ['attendanceCount','attendanceTotal'])if(b[key]!=null){if(!Number.isInteger(b[key])||b[key]<0)fail('Invalid student count.');s[key]=b[key];}if(s.attendanceCount!=null&&s.attendanceTotal!=null&&s.attendanceCount>s.attendanceTotal)fail('Present cannot exceed total.');if(b.coverage){if(!['full','partial','none'].includes(b.coverage))fail('Invalid coverage.');s.coverage=b.coverage;}}
    else fail('Unknown attendance action.');writeState(db,r.state,r.revision);audit(u,'Recorded '+b.action+' for '+s.id);return json(res,200,{ok:true});
   }
   if(path==='/api/attendance-review'&&method==='POST'){if(u.role!=='mentor')fail('Mentor access required.',403);const b=await body(req);if(!['entry','exit'].includes(b.stage)||!['approved','rejected'].includes(b.decision)||typeof b.note!=='string'||b.note.length>300||b.decision==='rejected'&&!b.note.trim())fail('Choose a decision and supply a rejection reason.');const r=readState(db),s=r.state.schedules.find(x=>x.id===b.id);if(!s||!s[b.stage==='entry'?'actualStart':'actualEnd']||(s[b.stage+'Review']?.status||'pending')!=='pending')fail('This time is not awaiting review.');s[b.stage+'Review']={status:b.decision,by:u.name,at:new Date().toISOString(),note:b.note.trim()};writeState(db,r.state,r.revision);audit(u,b.decision+' '+b.stage+' for '+s.id);return json(res,200,{ok:true});}
   fail('Not found.',404);
  }catch(e){if(!res.headersSent)json(res,e.status||500,{error:e.status?e.message:'Server error. No changes were confirmed.'});else res.end();if(!e.status)console.error('Request failed:',e.message);}
 });server.headersTimeout=15000;server.requestTimeout=30000;return {server,db};
}
if(process.argv[1]===fileURLToPath(import.meta.url)){
 const production=process.env.NODE_ENV==='production',origin=process.env.APP_ORIGIN||'http://127.0.0.1:3000',host=process.env.HOST||(production?'0.0.0.0':'127.0.0.1');if(!production&&!['127.0.0.1','localhost','::1'].includes(host))throw Error('Public binding requires NODE_ENV=production and an HTTPS APP_ORIGIN.');const {server}=await createApp({origin,production});server.listen(Number(process.env.PORT||3000),host,()=>console.log('TMS listening. Configure your HTTPS reverse proxy before public use.'));
}
