/* TMS student operations: local HTML edition */
const smsNormalizeBase=normalizeState;
normalizeState=function(s){s=smsNormalizeBase(s);for(const k of ['applications','assessments','invoices','payments','messages','exams','studentNotes','smsAudit'])s[k]=Array.isArray(s[k])?s[k]:[];return s;};
let smsTab='overview',smsStudent='',smsFrom='',smsTo=todayISO();
const smsTabs={overview:'Overview',profiles:'Student profiles',admissions:'Admissions',grades:'Grades & progress',exams:'Exam timetable',fees:'Fees & receipts',messages:'Communication',reports:'Reports',settings:'Access & integrations'};
function smsAdmin(){return isStakeholderView();}
function smsActor(){return isTeacherPersona()?facultyDisplay(currentUser.name):currentUser.coordinator.trim();}
function smsPeople(){return visibleStudents().filter(p=>!p.archived);}
function smsAllowed(){return smsAdmin()?Object.keys(smsTabs):isTeacherPersona()?['overview','profiles','grades','exams','reports']:[];}
function smsPerson(id){return smsPeople().find(p=>p.id===id);}
function smsName(id){return state.students.find(p=>p.id===id)?.name||'Archived student';}
function smsSafe(v){return /^[=+@\-\t\r]/.test(String(v??''))?"'"+v:v??'';}
function smsCSV(name,rows){downloadBlob(name+'.csv',toCSV(rows.map(r=>r.map(smsSafe))),'text/csv;charset=utf-8');}
function smsField(label,name,type='text',value='',extra=''){return `<div class="fg"><label for="sms-${name}">${label}</label><input id="sms-${name}" name="${name}" type="${type}" value="${esc(value)}" ${extra}></div>`;}
function smsText(label,name,value=''){return `<div class="fg"><label for="sms-${name}">${label}</label><textarea id="sms-${name}" name="${name}" rows="3" maxlength="3000">${esc(value)}</textarea></div>`;}
function smsSelect(label,name,options){return `<div class="fg"><label for="sms-${name}">${label}</label><select id="sms-${name}" name="${name}" required>${options}</select></div>`;}
function smsStudentOptions(){return '<option value="">Choose student</option>'+smsPeople().map(p=>`<option value="${esc(p.id)}" ${p.id===smsStudent?'selected':''}>${esc(p.name)} · ${esc(p.code)}</option>`).join('');}
function smsForm(kind,fields,label){return `<form data-sms-form="${kind}"><div class="form-grid">${fields}</div><div class="cc-actions"><button class="btn btn-teal">${label}</button></div></form>`;}
function smsTable(head,rows){return `<div class="table-wrap"><table><thead><tr>${head.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.join('')||`<tr><td colspan="${head.length}" class="empty">No records yet.</td></tr>`}</tbody></table></div>`;}
function smsCard(title,body){return `<section class="card"><h3>${title}</h3>${body}</section>`;}
function smsBtn(action,id,label){return `<button class="btn btn-outline btn-sm" data-sms-action="${action}" data-sms-id="${esc(id)}">${label}</button>`;}
function smsAttendance(id){let marked=0,present=0,absent=0,late=0;Object.entries(state.studentAttendance).forEach(([d,r])=>{if((smsFrom&&d<smsFrom)||d>smsTo||!r[id])return;const status=r[id].status;if(status==='excused')return;marked++;if(status==='present'||status==='late')present++;if(status==='absent')absent++;if(status==='late')late++;});return {marked,present,absent,late,rate:marked?Math.round(present/marked*100):null};}
function smsBalance(i){return i.amount-state.payments.filter(p=>p.invoiceId===i.id).reduce((n,p)=>n+p.amount,0);}
function smsMoney(cents){return 'INR '+(cents/100).toLocaleString('en-IN',{minimumFractionDigits:2,maximumFractionDigits:2});}
async function smsMutate(action,fn){if(!smsActor()){showToast('Enter your name in the sidebar first.');return false;}const before=JSON.stringify(state);try{fn();state.smsAudit.unshift({id:uid(),at:new Date().toISOString(),by:smsActor(),action});if(!await saveState()){state=normalizeState(JSON.parse(before));return false;}render();return true;}catch(e){state=normalizeState(JSON.parse(before));showToast(e.message);return false;}}
function smsRequireAdmin(){if(!smsAdmin())throw Error('This action belongs to the principal / coordinator view.');}
function smsValidatePerson(id){const p=smsPerson(id);if(!p)throw Error('Choose a student assigned to your view.');return p;}
function smsOverview(){const all=smsPeople(),pending=state.applications.filter(a=>a.status==='applied'||a.status==='waitlisted').length;return `<div class="kpi-grid">${kpiCard('Active students',String(all.length),'Central student register','','var(--teal)')}${kpiCard('Attendance follow-up',String(all.filter(p=>{const a=smsAttendance(p.id);return a.marked>=5&&a.rate<75;}).length),'Below 75% · at least 5 marked days','','var(--amber)')}${kpiCard('Assessments',String(state.assessments.filter(a=>all.some(p=>p.id===a.studentId)).length),'Recorded scores','','var(--indigo)')}${smsAdmin()?kpiCard('Open applications',String(pending),'Applied or waitlisted','','var(--green)'):''}</div>${smsCard('Student operations',`<div class="sms-tiles">${smsAllowed().filter(k=>k!=='overview').map(k=>`<button class="btn btn-outline" data-sms-tab="${k}">${smsTabs[k]}</button>`).join('')}</div><p class="hint">Use Student management for the register, bulk imports and daily attendance. Use Timetables for teaching schedules.</p>`)}${smsCard('Local edition',`<p>Records are stored in this browser. Role views are demonstrations, not authenticated accounts. Use sample data for medical and safeguarding fields until secure hosting is configured.</p><p class="hint">Messages are drafts. Payments are manually recorded. No external service is connected.</p>`)}`;}
function smsProfiles(){const p=smsPerson(smsStudent);return smsCard('Central student profile',`<div class="grid-toolbar"><label for="sms-person-pick">Student</label><select id="sms-person-pick">${smsStudentOptions()}</select></div>${!p?'<p class="empty">Select a student from the register.</p>':`<h3>${esc(p.name)} · ${esc(p.code)}</h3><p>${esc(studentProgram(p))} · ${esc(studentBatch(p))}</p>${smsAdmin()?smsForm('profile',`<input type="hidden" name="studentId" value="${p.id}">${smsField('Date of birth','dob','date',p.dob||'','max="'+todayISO()+'"')}${smsField('Guardian name','guardian','text',p.guardian||'','maxlength="100"')}${smsField('Guardian email','email','email',p.email||'')}${smsField('Emergency contact','emergency','tel',p.emergency||'','maxlength="100"')}${smsText('Address','address',p.address||'')}${smsText('Medical notes · sample data only','medical',p.medical||'')}${smsText('Academic history','history',p.history||'')}${smsText('Safeguarding notes · sample data only','safeguarding',p.safeguarding||'')}`,'Save profile'):`<p><strong>Academic history:</strong> ${esc(p.history||'Not recorded')}</p>`}<h3 style="margin-top:20px">Progress & behavior notes</h3>${smsForm('note',`<input type="hidden" name="studentId" value="${p.id}">${smsSelect('Category','category','<option>Progress</option><option>Behavior</option><option>Support</option>')}${smsText('Note','note')}`,'Save note')}${smsTable(['Date','Category','Note','Recorded by'],state.studentNotes.filter(n=>n.studentId===p.id).map(n=>`<tr><td>${esc(tmsTime(n.at))}</td><td>${esc(n.category)}</td><td>${esc(n.note)}</td><td>${esc(n.by)}</td></tr>`))}`}`);}
function smsAdmissions(){return smsCard('New application',`<p class="hint">Applications stay on this device. One document per application, PDF or image, up to 250 KB. Batch capacity uses the enrollment strength set in Admin.</p>${smsForm('application',smsField('Applicant name','name','text','','required maxlength="100"')+smsField('Admission number','code','text','','required maxlength="40"')+smsSelect('Requested batch','batchId','<option value="">Select batch</option>'+studentOptions())+smsField('Guardian contact','contact','tel','','maxlength="40"')+smsField('Supporting document','document','file','','accept=".pdf,.png,.jpg,.jpeg"'),'Save application')}`)+smsCard('Admissions pipeline',smsTable(['Applicant','Batch','Status','Document','Actions'],state.applications.map(a=>`<tr><td>${esc(a.name)}<div class="cc-meta">${esc(a.code)}</div></td><td>${esc(state.batches.find(b=>b.id===a.batchId)?.name||'Missing batch')}</td><td>${esc(a.status)}</td><td>${a.document?smsBtn('document',a.id,esc(a.document.name)):'—'}</td><td>${['applied','waitlisted'].includes(a.status)?smsBtn('enroll',a.id,'Enroll')+' '+smsBtn('waitlist',a.id,'Waitlist')+' '+smsBtn('decline',a.id,'Decline'):a.studentId?'Linked to student record':'—'}</td></tr>`)));}
function smsGradeRows(){const ids=new Set(smsPeople().map(p=>p.id));return state.assessments.filter(a=>ids.has(a.studentId)&&(!smsStudent||a.studentId===smsStudent));}
function smsGrades(){return smsCard('Record assessment',smsForm('grade',smsSelect('Student','studentId',smsStudentOptions())+smsField('Subject','subject','text','','required maxlength="100"')+smsField('Assessment / term','title','text','','required maxlength="100"')+smsField('Date','date','date',todayISO(),'required')+smsField('Marks earned','score','number','','required min="0" step="0.01"')+smsField('Maximum marks','max','number','100','required min="0.01" step="0.01"'),'Save assessment'))+smsCard('Gradebook & progress',`<div class="grid-toolbar"><label for="sms-person-pick">Filter student</label><select id="sms-person-pick">${smsStudentOptions()}</select>${smsBtn('grades-export','','Export progress CSV')}</div>${smsTable(['Student','Subject / assessment','Date','Score','Percentage',''],smsGradeRows().map(a=>`<tr><td>${esc(smsName(a.studentId))}</td><td>${esc(a.subject)} · ${esc(a.title)}</td><td>${esc(a.date)}</td><td>${a.score} / ${a.max}</td><td>${(a.score/a.max*100).toFixed(1)}%</td><td>${smsAdmin()||a.by===smsActor()?smsBtn('grade-remove',a.id,'Remove'):''}</td></tr>`))}<p class="hint">Exports contain recorded assessment scores; they are not certified transcripts.</p>`);}
function smsExams(){return (smsAdmin()?smsCard('Schedule exam',smsForm('exam',smsField('Exam title','title','text','','required maxlength="120"')+smsSelect('Batch','batchId','<option value="">Select batch</option>'+studentOptions())+smsField('Date','date','date',todayISO(),'required')+smsField('Start','startTime','time','','required')+smsField('End','endTime','time','','required')+smsSelect('Room','roomId','<option value="">Select room</option>'+state.classrooms.map(r=>`<option value="${r.id}">${esc(centerName(r.center))} · ${esc(r.name)}</option>`).join('')),'Schedule exam')):'')+smsCard('Exam timetable',smsTable(['Exam','Batch / room','Date','Time',''],state.exams.filter(e=>smsAdmin()||state.schedules.some(s=>s.faculty===currentUser.name&&s.batchId===e.batchId)).map(e=>`<tr><td>${esc(e.title)}</td><td>${esc(state.batches.find(b=>b.id===e.batchId)?.name||'—')} · ${esc(classroomName(e.roomId))}</td><td>${esc(e.date)}</td><td>${esc(e.startTime)}–${esc(e.endTime)}</td><td>${smsAdmin()?smsBtn('exam-remove',e.id,'Remove'):''}</td></tr>`)))+smsCard('Teaching timetable','<p>Use Schedules in the sidebar to create individual, recurring or imported teaching sessions. Exam creation checks room and cohort clashes against those sessions and other exams.</p>');}
function smsFees(){const total=state.invoices.reduce((n,i)=>n+smsBalance(i),0);return smsCard('Fee management · INR',`<p>Outstanding: <strong>${smsMoney(total)}</strong></p><p class="hint">Create one invoice per installment to build a payment plan. Payments are recorded manually. Receipts acknowledge recorded payments and are not tax receipts.</p>${smsForm('invoice',smsSelect('Student','studentId',smsStudentOptions())+smsField('Fee / installment description','description','text','','required maxlength="150"')+smsField('Amount (INR)','amount','number','','required min="0.01" step="0.01"')+smsField('Due date','due','date',todayISO(),'required'),'Create invoice')}`)+smsCard('Record payment',smsForm('payment',smsSelect('Invoice','invoiceId','<option value="">Choose unpaid invoice</option>'+state.invoices.filter(i=>smsBalance(i)>0).map(i=>`<option value="${i.id}">${esc(i.number)} · ${esc(smsName(i.studentId))} · ${smsMoney(smsBalance(i))}</option>`).join(''))+smsField('Amount received (INR)','amount','number','','required min="0.01" step="0.01"')+smsField('Payment date','date','date',todayISO(),'required max="'+todayISO()+'"')+smsField('Payment reference','reference','text','','required maxlength="100"'),'Record payment'))+smsCard('Invoices',smsTable(['Invoice','Student / description','Due','Amount','Balance',''],state.invoices.map(i=>`<tr><td>${esc(i.number)}</td><td>${esc(smsName(i.studentId))} · ${esc(i.description)}</td><td>${esc(i.due)} ${i.due<todayISO()&&smsBalance(i)>0?'· Overdue':''}</td><td>${smsMoney(i.amount)}</td><td>${smsMoney(smsBalance(i))}</td><td>${smsBtn('invoice-export',i.id,'Download invoice')}</td></tr>`)))+smsCard('Payment receipts',smsTable(['Receipt','Student','Amount','Date / reference',''],state.payments.map(p=>`<tr><td>${esc(p.number)}</td><td>${esc(smsName(state.invoices.find(i=>i.id===p.invoiceId)?.studentId))}</td><td>${smsMoney(p.amount)}</td><td>${esc(p.date)} · ${esc(p.reference)}</td><td>${smsBtn('receipt',p.id,'Download receipt')}</td></tr>`)));}
function smsMessages(){return smsCard('Communication drafts',`<p class="hint">Prepare broadcasts or absence alerts for review and export. No message is sent from this HTML page.</p>${smsForm('message',smsSelect('Audience','batchId','<option value="all">All active students</option>'+studentOptions())+smsField('Subject','subject','text','','required maxlength="150"')+smsText('Message','body'),'Save draft')}<div class="cc-actions">${smsBtn('absence-drafts','','Prepare today’s absence alerts')}${smsBtn('messages-export','','Export drafts CSV')}</div>`)+smsCard('Draft outbox',smsTable(['Created','Audience','Subject / message','Delivery'],state.messages.map(m=>`<tr><td>${esc(tmsTime(m.at))}</td><td>${m.studentId?esc(smsName(m.studentId)):m.batchId==='all'?'All active students':esc(state.batches.find(b=>b.id===m.batchId)?.name||'Batch')}</td><td><strong>${esc(m.subject)}</strong><div>${esc(m.body)}</div></td><td>Draft · not sent</td></tr>`)));}
function smsReports(){return smsCard('Student analytics',`<div class="grid-toolbar"><label for="sms-from">From</label><input id="sms-from" type="date" value="${esc(smsFrom)}"><label for="sms-to">To</label><input id="sms-to" type="date" value="${esc(smsTo)}">${smsBtn('report-export','','Export report')}</div><p class="hint">Attendance excludes unmarked and excused days; late counts as present. Follow-up flags use below 75% attendance after at least five marked days. Scores use total marks earned ÷ total maximum marks for the selected dates.</p>${smsTable(['Student','Attendance','Absences / late','Academic score','Follow-up'],smsReportRows().map(r=>`<tr>${r.map(v=>`<td>${esc(v)}</td>`).join('')}</tr>`))}`);}
function smsReportRows(){return smsPeople().map(p=>{const a=smsAttendance(p.id),grades=state.assessments.filter(g=>g.studentId===p.id&&(!smsFrom||g.date>=smsFrom)&&g.date<=smsTo),max=grades.reduce((n,g)=>n+g.max,0),score=grades.reduce((n,g)=>n+g.score,0);return [p.name+' · '+p.code,a.rate===null?'No marked days':a.rate+'% ('+a.present+'/'+a.marked+')',a.absent+' / '+a.late,max?(score/max*100).toFixed(1)+'%':'No assessments',a.marked>=5&&a.rate<75?'Attendance follow-up':'—'];});}
function smsSettings(){return smsCard('Access & data protection',`<p><strong>Local prototype — no secure authentication or encryption at rest.</strong> Anyone with access to this browser can change role views or inspect stored records. Parent and student portals are not enabled.</p><p>Medical notes, safeguarding data and supporting documents need protected server storage before real operational use. The activity log below is local and editable by anyone with browser access; it is not an immutable audit trail.</p><p>No GDPR or FERPA compliance certification is claimed.</p>`)+smsCard('Integrations & backup',`<p>No LMS, HR, finance, email, payment, RFID or biometric connection is configured. CSV exports support manual transfer. A hosted backend and provider configuration are required for live integrations.</p>${smsBtn('backup','','Download full JSON backup')}<p class="hint">The backup includes all locally saved records and uploaded application documents. Keep it private. This export does not connect to any external service.</p>`)+smsCard('Student operations activity',smsTable(['Time','Actor','Action'],state.smsAudit.slice(0,100).map(a=>`<tr><td>${esc(tmsTime(a.at))}</td><td>${esc(a.by)}</td><td>${esc(a.action)}</td></tr>`)));}
function renderSms(){const allowed=smsAllowed();if(!allowed.length)return smsCard('Unavailable','Choose a staff view to open student operations.');if(!allowed.includes(smsTab))smsTab='overview';return `<div class="sms-tabs">${allowed.map(k=>`<button class="btn ${smsTab===k?'btn-teal':'btn-outline'}" data-sms-tab="${k}">${smsTabs[k]}</button>`).join('')}</div>`+({overview:smsOverview,profiles:smsProfiles,admissions:smsAdmissions,grades:smsGrades,exams:smsExams,fees:smsFees,messages:smsMessages,reports:smsReports,settings:smsSettings}[smsTab])();}
const smsBodyBase=renderBody;renderBody=function(){return currentUser.role==='sms'?renderSms():smsBodyBase();};
async function smsReadFile(file){if(!file||!file.size)return null;if(file.size>250*1024)throw Error('Document must be 250 KB or smaller.');if(!['application/pdf','image/png','image/jpeg'].includes(file.type))throw Error('Use a PDF, PNG or JPEG document.');const data=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=()=>reject(Error('Could not read document.'));r.readAsDataURL(file);});return {name:file.name,type:file.type,data};}
function smsEnroll(id){smsRequireAdmin();const a=state.applications.find(a=>a.id===id);if(!a||!['applied','waitlisted'].includes(a.status))throw Error('Application cannot be enrolled.');const b=state.batches.find(b=>b.id===a.batchId);if(!b)throw Error('Batch no longer exists.');if(state.students.some(p=>p.code.toLowerCase()===a.code.toLowerCase()))throw Error('Admission number already exists.');const count=state.students.filter(p=>!p.archived&&p.batchId===b.id).length;if(b.strength&&count>=b.strength){a.status='waitlisted';return 'Batch full: applicant placed on waitlist.';}const p={id:uid(),name:a.name,code:a.code,contact:a.contact,programId:b.programId,batchId:b.id,applicationId:a.id};state.students.push(p);a.status='enrolled';a.studentId=p.id;return 'Applicant enrolled. Student record created.';}
function smsAddExam(v){smsRequireAdmin();const b=state.batches.find(b=>b.id===v.batchId),p=state.programs.find(p=>p.id===b?.programId),r=state.classrooms.find(r=>r.id===v.roomId);if(!p||!r||r.center!==p.center)throw Error('Choose a room at the program’s centre.');if(!v.title||!v.date||v.startTime>=v.endTime)throw Error('Enter a title, date and valid time range.');const overlap=x=>x.date===v.date&&x.startTime<v.endTime&&v.startTime<x.endTime;if(state.exams.some(x=>overlap(x)&&(x.roomId===v.roomId||x.batchId===v.batchId))||state.schedules.some(x=>x.status!=='cancelled'&&overlap(x)&&(x.classroom===v.roomId||(x.programId===p.id&&(!x.batchId||x.batchId===v.batchId)))))throw Error('Room or student batch clashes with an existing class or exam.');state.exams.push({id:uid(),...v});}
function smsCents(raw){if(!/^\d+(\.\d{1,2})?$/.test(raw))throw Error('Enter a positive amount with at most two decimal places.');const n=Math.round(Number(raw)*100);if(!Number.isSafeInteger(n)||n<=0||n>1e12)throw Error('Amount is outside the supported range.');return n;}
async function smsSubmit(kind,form){const v=Object.fromEntries(new FormData(form).entries());for(const k in v)if(typeof v[k]==='string')v[k]=v[k].trim();let document=null;try{if(kind==='application'){smsRequireAdmin();document=await smsReadFile(v.document);}}catch(e){showToast(e.message);return;}
 await smsMutate('Saved '+kind,()=>{
 if(kind==='profile'){smsRequireAdmin();const p=smsValidatePerson(v.studentId);if(v.dob&&v.dob>todayISO())throw Error('Birth date cannot be in the future.');for(const k of ['dob','guardian','email','emergency','address','medical','history','safeguarding'])p[k]=v[k];}
 else if(kind==='note'){smsValidatePerson(v.studentId);if(!v.note)throw Error('Enter a note.');state.studentNotes.unshift({id:uid(),...v,by:smsActor(),at:new Date().toISOString()});}
 else if(kind==='application'){smsRequireAdmin();if(!v.name||!v.code||!state.batches.some(b=>b.id===v.batchId))throw Error('Complete the applicant and batch fields.');if(state.students.some(p=>p.code.toLowerCase()===v.code.toLowerCase())||state.applications.some(a=>a.code.toLowerCase()===v.code.toLowerCase()))throw Error('Admission number already exists.');const b=state.batches.find(b=>b.id===v.batchId),full=b.strength&&state.students.filter(p=>!p.archived&&p.batchId===b.id).length>=b.strength;state.applications.push({id:uid(),name:v.name,code:v.code,batchId:v.batchId,contact:v.contact,document,status:full?'waitlisted':'applied',at:new Date().toISOString()});}
 else if(kind==='grade'){smsValidatePerson(v.studentId);const score=Number(v.score),max=Number(v.max);if(!v.subject||!v.title||!v.date||!Number.isFinite(score)||!Number.isFinite(max)||max<=0||score<0||score>max)throw Error('Check the assessment details; earned marks must be between zero and maximum.');if(state.assessments.some(a=>a.studentId===v.studentId&&a.subject.toLowerCase()===v.subject.toLowerCase()&&a.title.toLowerCase()===v.title.toLowerCase()&&a.date===v.date))throw Error('This assessment is already recorded.');state.assessments.push({id:uid(),...v,score,max,by:smsActor()});}
 else if(kind==='exam')smsAddExam(v);
 else if(kind==='invoice'){smsRequireAdmin();smsValidatePerson(v.studentId);if(!v.description||!v.due)throw Error('Description and due date required.');state.invoices.push({id:uid(),number:'INV-'+String(state.invoices.length+1).padStart(5,'0'),studentId:v.studentId,description:v.description,due:v.due,amount:smsCents(v.amount),at:new Date().toISOString()});}
 else if(kind==='payment'){smsRequireAdmin();const i=state.invoices.find(i=>i.id===v.invoiceId),amount=smsCents(v.amount);if(!i||amount>smsBalance(i))throw Error('Payment exceeds the outstanding invoice balance.');if(!v.date||v.date>todayISO()||!v.reference)throw Error('Enter a valid payment date and reference.');if(state.payments.some(p=>p.reference.toLowerCase()===v.reference.toLowerCase()))throw Error('Payment reference already recorded.');state.payments.push({id:uid(),number:'RCT-'+String(state.payments.length+1).padStart(5,'0'),...v,amount,by:smsActor()});}
 else if(kind==='message'){smsRequireAdmin();if(!v.subject||!v.body)throw Error('Enter a subject and message.');state.messages.unshift({id:uid(),...v,at:new Date().toISOString(),status:'draft'});}
 });
}
async function smsAction(action,id){
 try{
 if(action==='grades-export')return smsCSV('TMS-progress',[['Student','Subject','Assessment','Date','Score','Maximum'],...smsGradeRows().map(a=>[smsName(a.studentId),a.subject,a.title,a.date,a.score,a.max])]);
 if(action==='report-export')return smsCSV('TMS-student-report',[['Student','Attendance','Absent / late','Academic score','Follow-up'],...smsReportRows()]);
 if(action==='grade-remove'){const a=state.assessments.find(a=>a.id===id);if(!a||!smsPerson(a.studentId)||(!smsAdmin()&&a.by!==smsActor()))return;if(confirm('Remove this assessment score?'))await smsMutate('Removed assessment',()=>state.assessments=state.assessments.filter(a=>a.id!==id));return;}
 smsRequireAdmin();
 if(action==='backup')return downloadBlob('TMS-backup-'+todayISO()+'.json',JSON.stringify({format:'TMS-local-v2',exportedAt:new Date().toISOString(),data:state},null,2),'application/json');
 if(action==='messages-export')return smsCSV('TMS-message-drafts',[['Audience','Guardian contact','Subject','Message','Status'],...state.messages.map(m=>[m.studentId?smsName(m.studentId):m.batchId==='all'?'All students':state.batches.find(b=>b.id===m.batchId)?.name||'',m.studentId?state.students.find(p=>p.id===m.studentId)?.contact||'':'',m.subject,m.body,'Draft - not sent'])]);
 if(action==='document'){const doc=state.applications.find(a=>a.id===id)?.document;if(!doc)return;const bytes=Uint8Array.from(atob(doc.data.split(',')[1]),c=>c.charCodeAt(0));return downloadBlob(doc.name,bytes,doc.type);}
 if(action==='invoice-export'){const i=state.invoices.find(i=>i.id===id);if(i)return downloadBlob(i.number+'.txt',`TMS FEE INVOICE\n${i.number}\nStudent: ${smsName(i.studentId)}\nDescription: ${i.description}\nDue: ${i.due}\nAmount: ${smsMoney(i.amount)}\nOutstanding: ${smsMoney(smsBalance(i))}\nLocal record. Not a tax invoice.`,'text/plain');return;}
 if(action==='receipt'){const p=state.payments.find(p=>p.id===id),i=state.invoices.find(i=>i.id===p?.invoiceId);if(p&&i)return downloadBlob(p.number+'.txt',`TMS PAYMENT ACKNOWLEDGMENT\n${p.number}\nInvoice: ${i.number}\nStudent: ${smsName(i.studentId)}\nReceived: ${smsMoney(p.amount)}\nDate: ${p.date}\nReference: ${p.reference}\nRecorded by: ${p.by}\nManually recorded payment; not a tax receipt.`,'text/plain');return;}
 let message='';await smsMutate(action,()=>{
 if(action==='enroll')message=smsEnroll(id);
 else if(action==='waitlist'||action==='decline'){const a=state.applications.find(a=>a.id===id);if(a&&['applied','waitlisted'].includes(a.status))a.status=action==='waitlist'?'waitlisted':'declined';}
 else if(action==='exam-remove')state.exams=state.exams.filter(e=>e.id!==id);
 else if(action==='absence-drafts'){let count=0;const date=todayISO();for(const p of smsPeople()){if(state.studentAttendance[date]?.[p.id]?.status!=='absent'||state.messages.some(m=>m.studentId===p.id&&m.absenceDate===date))continue;state.messages.unshift({id:uid(),studentId:p.id,absenceDate:date,subject:'Attendance follow-up · '+date,body:`Dear parent/guardian, ${p.name} was marked absent on ${date}. Please contact the institution to confirm the reason.`,at:new Date().toISOString(),status:'draft'});count++;}message=count+' absence drafts prepared. Nothing has been sent.';}
 });if(message)showToast(message,5000);
 }catch(e){showToast(e.message);}
}
const smsHandlersBase=attachHandlers;attachHandlers=function(){smsHandlersBase();
 document.querySelectorAll('[data-sms-tab]').forEach(b=>b.onclick=()=>{smsTab=b.dataset.smsTab;render();});
 document.querySelectorAll('[data-sms-form]').forEach(f=>f.onsubmit=async e=>{e.preventDefault();const b=f.querySelector('button');if(b.disabled)return;b.disabled=true;try{await smsSubmit(f.dataset.smsForm,f);}finally{b.disabled=false;}});
 document.querySelectorAll('[data-sms-action]').forEach(b=>b.onclick=async()=>{if(b.disabled)return;b.disabled=true;try{await smsAction(b.dataset.smsAction,b.dataset.smsId);}finally{b.disabled=false;}});
 const picker=document.getElementById('sms-person-pick');if(picker)picker.onchange=e=>{smsStudent=e.target.value;render();};
 for(const key of ['from','to']){const el=document.getElementById('sms-'+key);if(el)el.onchange=()=>{const from=document.getElementById('sms-from').value,to=document.getElementById('sms-to').value;if(!to||(from&&from>to))return showToast('Choose a valid date range.');smsFrom=from;smsTo=to;render();};}
 // Prevent existing student removal from orphaning academic or financial records.
 document.querySelectorAll('[data-student-remove]').forEach(b=>b.onclick=async()=>{if(!smsAdmin())return;const id=b.dataset.studentRemove;if(state.invoices.some(i=>i.studentId===id)||state.assessments.some(a=>a.studentId===id)||state.applications.some(a=>a.studentId===id)||state.studentNotes.some(n=>n.studentId===id)||state.messages.some(m=>m.studentId===id)){showToast('This student has linked records. Keep the profile to preserve their history.');return;}const p=state.students.find(p=>p.id===id);if(p&&confirm('Remove '+p.name+' and their attendance records?'))await smsMutate('Removed student',()=>{state.students=state.students.filter(p=>p.id!==id);Object.values(state.studentAttendance).forEach(r=>delete r[id]);});});
};
