import {fail,token,log,readState,writeState} from './store.mjs';
import {management} from './policy.mjs';
const text=(v,max=4000)=>{if(typeof v!=='string'||!v.trim()||v.length>max)fail('Enter valid text (maximum '+max+' characters).');return v.trim();};
const day=()=>new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Kolkata'});
const date=v=>{if(typeof v!=='string'||!/^\d{4}-\d{2}-\d{2}$/.test(v)||!Number.isFinite(Date.parse(v+'T00:00:00Z'))||new Date(v+'T00:00:00Z').toISOString().slice(0,10)!==v)fail('Invalid date.');return v;};
const email=v=>{if(typeof v!=='string'||v.length>254||!/^[^\s@,<>]+@[^\s@,<>]+\.[^\s@,<>]+$/.test(v))fail('Enter a valid recipient email address.');return v;};
export function canTeachBatch(s,u,batchId){const b=s.batches.find(b=>b.id===batchId);return !!b&&(management(u)||(u.role==='teacher'&&s.schedules.some(x=>x.faculty===u.faculty&&x.programId===b.programId&&(!x.batchId||x.batchId===batchId))));}
function canReadItem(s,u,item){if(item.archived)return false;return canTeachBatch(s,u,item.batchId)||(u.role==='student'&&s.students.some(p=>p.id===u.student_id&&p.batchId===item.batchId));}
function cleanFile(f){if(!f)return null;if(!['application/pdf','image/png','image/jpeg','text/plain'].includes(f.type)||typeof f.name!=='string'||f.name.length>150||typeof f.data!=='string'||f.data.length>700000||!new RegExp('^data:'+f.type.replace('/','\\/')+';base64,[A-Za-z0-9+/=]+$').test(f.data))fail('Use a PDF, PNG, JPEG or text file up to 500 KB.');if(Buffer.from(f.data.split(',')[1],'base64').length>500*1024)fail('File exceeds 500 KB.');return {name:f.name,type:f.type,data:f.data};}
export function createERP({db,json,body,audit,emailSender}){
 db.exec(`CREATE TABLE IF NOT EXISTS erp_items(id TEXT PRIMARY KEY,kind TEXT NOT NULL,actor_id TEXT NOT NULL,body TEXT NOT NULL);
 CREATE TABLE IF NOT EXISTS erp_submissions(id TEXT PRIMARY KEY,item_id TEXT NOT NULL REFERENCES erp_items(id),user_id TEXT NOT NULL,student_id TEXT NOT NULL,body TEXT NOT NULL,UNIQUE(item_id,student_id));
 CREATE TABLE IF NOT EXISTS erp_messages(id TEXT PRIMARY KEY,sender TEXT NOT NULL,recipient TEXT NOT NULL,subject TEXT NOT NULL,message TEXT NOT NULL,created TEXT NOT NULL,read_at TEXT);
 CREATE INDEX IF NOT EXISTS erp_inbox ON erp_messages(recipient,created);
 CREATE TABLE IF NOT EXISTS erp_email(id TEXT PRIMARY KEY,creator TEXT NOT NULL,recipient TEXT NOT NULL,subject TEXT NOT NULL,message TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'draft',provider_id TEXT,error TEXT,attempted_at TEXT);
 CREATE TABLE IF NOT EXISTS erp_registration_fields(id TEXT PRIMARY KEY,name TEXT NOT NULL);`);
 function contacts(s,u){const users=db.prepare('SELECT id,name,role,faculty,student_id FROM users WHERE disabled=0').all();return users.filter(x=>{if(x.id===u.id)return false;if(management(u))return true;if(u.role==='student'){const p=s.students.find(p=>p.id===u.student_id);return management(x)||x.role==='teacher'&&p&&canTeachBatch(s,x,p.batchId);}if(x.role!=='student')return true;return u.role==='teacher'&&s.students.some(p=>p.id===x.student_id&&canTeachBatch(s,u,p.batchId));}).map(x=>({id:x.id,name:x.name,role:x.role}));}
 function requireManagement(u){if(!management(u))fail('Principal/coordinator access required.',403);}
 function allItems(){return db.prepare('SELECT * FROM erp_items').all().map(x=>({...JSON.parse(x.body),id:x.id,kind:x.kind,actorId:x.actor_id}));}
 function item(id){const r=db.prepare('SELECT * FROM erp_items WHERE id=?').get(id);if(!r)fail('Learning item not found.',404);return {...JSON.parse(r.body),id:r.id,kind:r.kind,actorId:r.actor_id};}
 function publicItem(i,u){const copy=structuredClone(i);if(u.role==='student'&&copy.questions)copy.questions=copy.questions.map(q=>({prompt:q.prompt,options:q.options}));return copy;}
 function mySubmission(r){const b=JSON.parse(r.body);return {id:r.id,itemId:r.item_id,studentId:r.student_id,...b,file:b.file?{name:b.file.name,type:b.file.type}:null};}
 async function sendViaResend(record){if(!process.env.RESEND_API_KEY||!process.env.EMAIL_FROM)fail('Email provider is not configured. Ask the administrator to set RESEND_API_KEY and EMAIL_FROM on the host.',503);const response=await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:'Bearer '+process.env.RESEND_API_KEY,'Content-Type':'application/json','Idempotency-Key':'tms-email-'+record.id},body:JSON.stringify({from:process.env.EMAIL_FROM,to:[record.recipient],subject:record.subject,text:record.message,...(process.env.EMAIL_REPLY_TO?{reply_to:email(process.env.EMAIL_REPLY_TO)}:{})}),signal:AbortSignal.timeout(15000)});if(!response.ok)throw Error('Provider returned HTTP '+response.status);const result=await response.json();if(typeof result.id!=='string')throw Error('Provider response did not confirm acceptance.');return result.id;}
 return async function route(req,res,path,u){
  if(!path.startsWith('/api/erp/'))return false;const s=readState(db).state,method=req.method;
  if(path==='/api/erp/overview'&&method==='GET'){return json(res,200,{contacts:contacts(s,u),emailConfigured:!!emailSender||!!(process.env.RESEND_API_KEY&&process.env.EMAIL_FROM),unread:db.prepare('SELECT COUNT(*) AS n FROM erp_messages WHERE recipient=? AND read_at IS NULL').get(u.id).n});}
  if(path==='/api/erp/messages'&&method==='GET'){const rows=db.prepare('SELECT m.*,a.name AS senderName,b.name AS recipientName FROM erp_messages m JOIN users a ON a.id=m.sender JOIN users b ON b.id=m.recipient WHERE m.sender=? OR m.recipient=? ORDER BY m.created DESC LIMIT 300').all(u.id,u.id);return json(res,200,{messages:rows});}
  if(path==='/api/erp/messages'&&method==='POST'){const b=await body(req),subject=text(b.subject,150),message=text(b.message,6000);const allowed=contacts(s,u),ids=b.audience==='staff'?(requireManagement(u),allowed.filter(x=>x.role!=='student').map(x=>x.id)):b.audience==='batch'?(requireManagement(u),db.prepare('SELECT id,student_id FROM users WHERE disabled=0 AND role=?').all('student').filter(x=>s.students.some(p=>p.id===x.student_id&&p.batchId===b.batchId)).map(x=>x.id)):[b.recipient];if(!ids.length||ids.length>500||ids.some(id=>!allowed.some(x=>x.id===id)))fail('Choose an authorized recipient or a batch with active student accounts.');db.exec('BEGIN');try{for(const id of new Set(ids))db.prepare('INSERT INTO erp_messages VALUES(?,?,?,?,?,?,NULL)').run(token(),u.id,id,subject,message,new Date().toISOString());log(db,u.username,'Sent internal message to '+ids.length+' account(s)');db.exec('COMMIT');}catch(e){db.exec('ROLLBACK');throw e;}return json(res,201,{ok:true,count:ids.length});}
  if(path==='/api/erp/messages/read'&&method==='POST'){const b=await body(req);const result=db.prepare('UPDATE erp_messages SET read_at=? WHERE id=? AND recipient=?').run(new Date().toISOString(),b.id,u.id);if(!result.changes)fail('Message not found.',404);return json(res,200,{ok:true});}
  if(path==='/api/erp/email'&&method==='GET'){requireManagement(u);return json(res,200,{emails:db.prepare('SELECT * FROM erp_email ORDER BY rowid DESC LIMIT 200').all(),configured:!!emailSender||!!(process.env.RESEND_API_KEY&&process.env.EMAIL_FROM)});}
  if(path==='/api/erp/email'&&method==='POST'){requireManagement(u);const b=await body(req);const id=token();db.prepare('INSERT INTO erp_email(id,creator,recipient,subject,message) VALUES(?,?,?,?,?)').run(id,u.id,email(b.recipient),text(b.subject,150),text(b.message,12000));audit(u,'Created email draft');return json(res,201,{id});}
  if(path==='/api/erp/email/send'&&method==='POST'){requireManagement(u);const b=await body(req);const r=db.prepare('SELECT * FROM erp_email WHERE id=?').get(b.id);if(!r)fail('Email not found.',404);if(b.confirm!==true)fail('Confirm the recipient and message before sending.');if(r.status==='accepted')return json(res,200,{status:'accepted'});if(r.status!=='draft'&&r.status!=='failed')fail('This email is pending confirmation of its previous send. Do not resend it automatically.',409);if(!emailSender&&(!process.env.RESEND_API_KEY||!process.env.EMAIL_FROM))fail('Email setup is required before sending.',503);db.prepare('UPDATE erp_email SET status=?,attempted_at=?,error=NULL WHERE id=?').run('sending',new Date().toISOString(),r.id);try{const providerId=await (emailSender||sendViaResend)(r);db.prepare('UPDATE erp_email SET status=?,provider_id=? WHERE id=?').run('accepted',providerId,r.id);audit(u,'Email accepted by provider '+r.id);return json(res,200,{status:'accepted'});}catch(e){db.prepare('UPDATE erp_email SET status=?,error=? WHERE id=?').run('uncertain','Provider acceptance could not be confirmed. Check the provider dashboard before creating another email.',r.id);return json(res,502,{error:'Could not confirm email acceptance. Check the provider dashboard; do not resend blindly.'});}}
  if(path==='/api/erp/learning'&&method==='GET'){const items=allItems().filter(i=>canReadItem(s,u,i));const ids=new Set(items.map(i=>i.id));const submissions=db.prepare('SELECT * FROM erp_submissions').all().filter(r=>ids.has(r.item_id)&&(u.role!=='student'||r.student_id===u.student_id)).map(mySubmission);return json(res,200,{items:items.map(i=>publicItem(i,u)),submissions});}
  if(path==='/api/erp/learning'&&method==='POST'){const b=await body(req);if(!canTeachBatch(s,u,b.batchId))fail('You cannot publish to this batch.',403);if(!['lesson','worksheet','quiz'].includes(b.kind))fail('Choose a learning item type.');const data={title:text(b.title,150),batchId:b.batchId,description:text(b.description,6000),created:new Date().toISOString(),archived:false};if(b.url){let link;try{link=new URL(b.url);}catch{fail('Use a valid HTTPS resource link.');}if(link.protocol!=='https:')fail('Resource links must use HTTPS.');data.url=link.href;}if(b.kind!=='lesson')data.due=date(b.due);if(b.kind==='quiz'){if(!Array.isArray(b.questions)||!b.questions.length||b.questions.length>10)fail('Add 1–10 questions.');data.questions=b.questions.map(q=>{if(!Array.isArray(q.options)||q.options.length!==4||!Number.isInteger(q.answer)||q.answer<0||q.answer>3)fail('Each question needs four choices and a correct answer.');return {prompt:text(q.prompt,500),options:q.options.map(x=>text(x,300)),answer:q.answer};});}const id=token();db.prepare('INSERT INTO erp_items VALUES(?,?,?,?)').run(id,b.kind,u.id,JSON.stringify(data));audit(u,'Published '+b.kind+' '+id);return json(res,201,{id});}
  if(path==='/api/erp/learning/archive'&&method==='POST'){const b=await body(req),i=item(b.id);if(!canTeachBatch(s,u,i.batchId)||!management(u)&&i.actorId!==u.id)fail('You cannot archive this item.',403);i.archived=true;db.prepare('UPDATE erp_items SET body=? WHERE id=?').run(JSON.stringify(i),i.id);audit(u,'Archived learning item '+i.id);return json(res,200,{ok:true});}
  if(path==='/api/erp/submissions'&&method==='POST'){if(u.role!=='student')fail('Student access required.',403);const b=await body(req),i=item(b.itemId);if(!canReadItem(s,u,i)||i.kind==='lesson')fail('Assignment not available.',403);if(i.due<day())fail('The submission deadline has passed.');if(db.prepare('SELECT id FROM erp_submissions WHERE item_id=? AND student_id=?').get(i.id,u.student_id))fail('You have already submitted this item.',409);let answer;if(i.kind==='quiz'){if(!Array.isArray(b.answers)||b.answers.length!==i.questions.length||b.answers.some(x=>!Number.isInteger(x)||x<0||x>3))fail('Answer every question.');answer={answers:b.answers,score:i.questions.reduce((n,q,index)=>n+(b.answers[index]===q.answer?1:0),0),max:i.questions.length,status:'graded'};}else{const file=cleanFile(b.file);const response=typeof b.response==='string'?b.response.trim():'';if((!response&&!file)||response.length>12000)fail('Enter your response or attach a worksheet.');answer={response,file,status:'submitted'};}answer.at=new Date().toISOString();const id=token();db.prepare('INSERT INTO erp_submissions VALUES(?,?,?,?,?)').run(id,i.id,u.id,u.student_id,JSON.stringify(answer));audit(u,'Submitted '+i.kind+' '+i.id);return json(res,201,{id,score:answer.score,max:answer.max});}
  if(path==='/api/erp/submissions/grade'&&method==='POST'){const b=await body(req),r=db.prepare('SELECT * FROM erp_submissions WHERE id=?').get(b.id);if(!r)fail('Submission not found.',404);const i=item(r.item_id);if(!canTeachBatch(s,u,i.batchId)||i.kind!=='worksheet')fail('You cannot grade this submission.',403);if(!Number.isFinite(b.score)||!Number.isFinite(b.max)||b.max<=0||b.score<0||b.score>b.max)fail('Invalid marks.');const value=JSON.parse(r.body);Object.assign(value,{score:b.score,max:b.max,feedback:typeof b.feedback==='string'?b.feedback.slice(0,3000):'',status:'graded',gradedBy:u.id,gradedAt:new Date().toISOString()});db.prepare('UPDATE erp_submissions SET body=? WHERE id=?').run(JSON.stringify(value),r.id);audit(u,'Graded worksheet '+r.id);return json(res,200,{ok:true});}
  if(path==='/api/erp/submissions/file'&&method==='POST'){const b=await body(req),r=db.prepare('SELECT * FROM erp_submissions WHERE id=?').get(b.id);if(!r)fail('File not found.',404);const i=item(r.item_id);if(!(u.role==='student'&&r.student_id===u.student_id)&&!canTeachBatch(s,u,i.batchId))fail('File access denied.',403);return json(res,200,{file:JSON.parse(r.body).file||null});}
  if(path==='/api/erp/schedule'&&method==='POST'){requireManagement(u);const b=await body(req),r=readState(db),batch=r.state.batches.find(x=>x.id===b.batchId),program=r.state.programs.find(x=>x.id===batch?.programId),teacher=r.state.faculty.find(x=>x.id===b.faculty),room=r.state.classrooms.find(x=>x.id===b.roomId);if(!batch||!program||!teacher||!room||room.center!==program.center||!teacher.centers.includes(program.center)||!teacher.verticals.includes(program.vertical))fail('Choose a teacher and room mapped to the selected program.');date(b.from);date(b.to);if(b.from>b.to||!Array.isArray(b.days)||!b.days.length||b.days.some(n=>!Number.isInteger(n)||n<0||n>6)||!/^\d{2}:\d{2}$/.test(b.start)||!/^\d{2}:\d{2}$/.test(b.end))fail('Choose a valid date range, weekdays and daily window.');const minutes=x=>{const [h,m]=x.split(':').map(Number);if(h>23||m>59)fail('Invalid time.');return h*60+m;},start=minutes(b.start),end=minutes(b.end),duration=Number(b.duration);if(!Number.isInteger(duration)||duration<15||duration>240||end-start<duration)fail('Choose a 15–240 minute lesson duration within the time window.');if((Date.parse(b.to)-Date.parse(b.from))/86400000>90)fail('Generate up to 90 days at a time.');const subject=text(b.subject,100),created=[],skipped=[];for(let d=new Date(b.from+'T00:00:00Z');d<=new Date(b.to+'T00:00:00Z');d.setUTCDate(d.getUTCDate()+1)){if(!b.days.includes(d.getUTCDay()))continue;const dateText=d.toISOString().slice(0,10);let found=false;for(let t=start;t+duration<=end;t+=15){const fmt=m=>String(Math.floor(m/60)).padStart(2,'0')+':'+String(m%60).padStart(2,'0'),a=fmt(t),z=fmt(t+duration);const clash=r.state.schedules.some(x=>x.status!=='cancelled'&&x.date===dateText&&x.startTime<z&&a<x.endTime&&(x.faculty===teacher.id||x.classroom===room.id||x.programId===program.id&&(!x.batchId||x.batchId===batch.id)))||r.state.exams.some(x=>x.date===dateText&&x.startTime<z&&a<x.endTime&&(x.roomId===room.id||x.batchId===batch.id));if(clash)continue;const record={id:token(),faculty:teacher.id,center:program.center,vertical:program.vertical,programId:program.id,program:program.name,batchId:batch.id,batch:batch.name,classroom:room.id,subject,chapter:'',lectureNo:'',date:dateText,day:['SUNDAY','MONDAY','TUESDAY','WEDNESDAY','THURSDAY','FRIDAY','SATURDAY'][d.getUTCDay()],startTime:a,endTime:z,status:'scheduled',sessionType:'academic',category:'Lecture',mode:'offline',link:'',actualStart:null,actualEnd:null,attendanceCount:null,attendanceTotal:null,coverage:null,createdAt:new Date().toISOString()};created.push(record);r.state.schedules.push(record);found=true;break;}if(!found)skipped.push(dateText);}if(b.commit===true){if(b.revision!==r.revision)fail('Timetable changed. Preview again.',409);writeState(db,r.state,r.revision);audit(u,'Generated '+created.length+' lesson slots');}return json(res,200,{created,skipped,revision:r.revision});}
  fail('ERP endpoint not found.',404);
 };
}
